import React, { useEffect, useMemo, useState } from "react";
import { Api } from "@/lib/api";
import { AppShell } from "@/app/components/AppShell";
import { Trash2, Eye, Sparkles, Search, Users, Building2, MapPin, Mail, Phone, Calendar, Zap, ArrowUpDown, ArrowUp, ArrowDown, Filter, X, Clock, CheckCircle, AlertCircle, TrendingUp, ChevronLeft, ChevronRight } from "lucide-react";
// @ts-ignore - This is an autogenerated file outside of src
import { projectId } from "/utils/supabase/info";

type Lead = any;

// Helper to format date in CST timezone
function formatDateCST(isoString: string) {
  if (!isoString) return "—";
  try {
    const date = new Date(isoString);
    return date.toLocaleString("en-US", {
      timeZone: "America/Chicago",
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    });
  } catch {
    return "—";
  }
}

// Helper to format short date
function formatShortDate(isoString: string) {
  if (!isoString) return "—";
  try {
    const date = new Date(isoString);
    return date.toLocaleString("en-US", {
      timeZone: "America/Chicago",
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return "—";
  }
}

type SortField = "name" | "company" | "title" | "email" | "phone" | "added" | "status" | "qualification" | "followUp";
type SortDirection = "asc" | "desc" | null;

export function LeadsPage({ onGoCampaigns, onNav, tab: initialTab }: { onGoCampaigns: () => void; onNav: (key: string, data?: any) => void; tab?: "discovered" | "enriched" }) {
  const [tab, setTab] = useState<"discovered" | "enriched">(initialTab || "discovered");
  const [loading, setLoading] = useState(true);
  const [leads, setLeads] = useState<Lead[]>([]);
  const [activities, setActivities] = useState<any[]>([]);
  const [q, setQ] = useState("");
  const [selectedLeads, setSelectedLeads] = useState<string[]>([]);
  const [enriching, setEnriching] = useState(false);
  const [enrichingSingle, setEnrichingSingle] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  // New filter states
  const [statusFilter, setStatusFilter] = useState<string | null>(null);
  const [qualificationFilter, setQualificationFilter] = useState<string | null>(null);
  const [followUpFilter, setFollowUpFilter] = useState<"upcoming" | "overdue" | null>(null);
  const [contactedFilter, setContactedFilter] = useState<boolean | null>(null);

  // Sorting state
  const [sortField, setSortField] = useState<SortField | null>(null);
  const [sortDirection, setSortDirection] = useState<SortDirection>(null);

  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);

  useEffect(() => {
    load();
  }, []);

  useEffect(() => {
    load();
  }, [tab]);

  useEffect(() => {
    // Update tab when initialTab prop changes
    if (initialTab) {
      setTab(initialTab);
    }
  }, [initialTab]);

  // Reset to page 1 when filters, search, or sorting changes
  useEffect(() => {
    setCurrentPage(1);
  }, [q, statusFilter, qualificationFilter, followUpFilter, contactedFilter, sortField, sortDirection]);

  async function load() {
    try {
      setLoading(true);
      setError(null);
      
      // Load leads based on current tab
      console.log(`[LEADS] Loading ${tab} leads...`);
      
      let leads;
      if (tab === "enriched") {
        // Enriched tab: Only show leads with enrichment_status = "complete"
        leads = await Api.listLeads({ enrichment_status: "complete" });
      } else {
        // Discovered tab: Show all leads, then filter out enriched ones
        const allLeads = await Api.listLeads();
        leads = allLeads.filter(l => l.enrichment_status !== "complete");
      }
      
      console.log(`[LEADS] Loaded ${leads?.length || 0} ${tab} leads`);
      setLeads(leads || []);

      // Load all activities to get follow-up data
      if (tab === "enriched") {
        try {
          // Fetch all activities in parallel instead of sequentially
          const activityPromises = (leads || []).map(lead => 
            Api.getLeadActivities(lead.id).catch(e => {
              console.warn(`[ACTIVITIES] Failed to load activities for lead ${lead.id}:`, e);
              return []; // Return empty array on error
            })
          );
          
          const activityResults = await Promise.all(activityPromises);
          const allActivities = activityResults.flat();
          
          console.log(`[ACTIVITIES] Loaded ${allActivities.length} total activities for ${leads.length} leads`);
          setActivities(allActivities);
        } catch (e) {
          console.error('[ACTIVITIES] Error loading activities:', e);
        }
      }
    } catch (e: any) {
      console.error('[LEADS] Error loading leads:', e);
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }

  // Enhanced filtering with status, qualification, follow-up, and contacted filters
  const filtered = useMemo(() => {
    const s = q.trim().toLowerCase();
    let result = leads;

    // Text search
    if (s) {
      result = result.filter((l) => {
        const name = `${l.first_name ?? ""} ${l.last_name ?? ""}`.toLowerCase();
        const company = `${l.company_name ?? ""}`.toLowerCase();
        const title = `${l.title ?? ""}`.toLowerCase();
        const email = `${l.email ?? ""}`.toLowerCase();
        return name.includes(s) || company.includes(s) || title.includes(s) || email.includes(s);
      });
    }

    // Status filter
    if (statusFilter) {
      result = result.filter((l) => l.status === statusFilter);
    }

    // Qualification filter
    if (qualificationFilter) {
      result = result.filter((l) => {
        const qual = l.qualification_level || 'cold';
        return qual === qualificationFilter;
      });
    }

    // Contacted filter
    if (contactedFilter !== null) {
      result = result.filter((l) => {
        const leadActivities = activities.filter(a => a.lead_id === l.id);
        const hasContact = leadActivities.some(a => 
          a.activity_type === "call" || a.activity_type === "email"
        );
        return contactedFilter ? hasContact : !hasContact;
      });
    }

    // Follow-up filter
    if (followUpFilter) {
      const now = new Date();
      result = result.filter((l) => {
        const leadActivities = activities.filter(a => a.lead_id === l.id);
        const upcomingFollowUps = leadActivities.filter(a => 
          a.follow_up_date && !a.follow_up_completed
        );
        
        if (upcomingFollowUps.length === 0) return false;
        
        const nextFollowUp = upcomingFollowUps.reduce((earliest, current) => {
          const currentDate = new Date(current.follow_up_date);
          const earliestDate = new Date(earliest.follow_up_date);
          return currentDate < earliestDate ? current : earliest;
        });

        const followUpDate = new Date(nextFollowUp.follow_up_date);
        
        if (followUpFilter === "overdue") {
          return followUpDate < now;
        } else {
          return followUpDate >= now;
        }
      });
    }

    return result;
  }, [leads, q, statusFilter, qualificationFilter, followUpFilter, contactedFilter, activities]);

  // Sorting logic
  const sorted = useMemo(() => {
    if (!sortField || !sortDirection) return filtered;

    return [...filtered].sort((a, b) => {
      let aVal: any;
      let bVal: any;

      switch (sortField) {
        case "name":
          aVal = `${a.first_name ?? ""} ${a.last_name ?? ""}`.toLowerCase();
          bVal = `${b.first_name ?? ""} ${b.last_name ?? ""}`.toLowerCase();
          break;
        case "company":
          aVal = (a.company_name ?? "").toLowerCase();
          bVal = (b.company_name ?? "").toLowerCase();
          break;
        case "title":
          aVal = (a.title ?? "").toLowerCase();
          bVal = (b.title ?? "").toLowerCase();
          break;
        case "email":
          aVal = (a.email ?? "").toLowerCase();
          bVal = (b.email ?? "").toLowerCase();
          break;
        case "phone":
          aVal = a.phone ?? "";
          bVal = b.phone ?? "";
          break;
        case "added":
          aVal = new Date(a.created_at || 0).getTime();
          bVal = new Date(b.created_at || 0).getTime();
          break;
        case "status":
          aVal = a.status ?? "";
          bVal = b.status ?? "";
          break;
        case "qualification":
          const qualOrder = { hot: 3, warm: 2, cold: 1 };
          const aQual = a.qualification_level || 'cold';
          const bQual = b.qualification_level || 'cold';
          aVal = qualOrder[aQual as keyof typeof qualOrder] ?? 0;
          bVal = qualOrder[bQual as keyof typeof qualOrder] ?? 0;
          break;
        case "followUp":
          const aActivities = activities.filter(act => act.lead_id === a.id && act.follow_up_date && !act.follow_up_completed);
          const bActivities = activities.filter(act => act.lead_id === b.id && act.follow_up_date && !act.follow_up_completed);
          aVal = aActivities.length > 0 ? new Date(aActivities[0].follow_up_date).getTime() : Infinity;
          bVal = bActivities.length > 0 ? new Date(bActivities[0].follow_up_date).getTime() : Infinity;
          break;
        default:
          return 0;
      }

      if (aVal < bVal) return sortDirection === "asc" ? -1 : 1;
      if (aVal > bVal) return sortDirection === "asc" ? 1 : -1;
      return 0;
    });
  }, [filtered, sortField, sortDirection, activities]);

  const handleSort = (field: SortField) => {
    if (sortField === field) {
      // Cycle through: asc -> desc -> null
      if (sortDirection === "asc") {
        setSortDirection("desc");
      } else if (sortDirection === "desc") {
        setSortDirection(null);
        setSortField(null);
      }
    } else {
      setSortField(field);
      setSortDirection("asc");
    }
  };

  const clearAllFilters = () => {
    setStatusFilter(null);
    setQualificationFilter(null);
    setFollowUpFilter(null);
    setContactedFilter(null);
    setQ("");
  };

  const hasActiveFilters = statusFilter || qualificationFilter || followUpFilter !== null || contactedFilter !== null || q;

  // Statistics for filter blocks
  const stats = useMemo(() => {
    const statusCounts = {
      new: 0,
      contacted: 0,
      qualified: 0,
      proposal: 0,
      won: 0,
      lost: 0,
    };
    const qualCounts = { cold: 0, warm: 0, hot: 0 };
    let contactedCount = 0;
    let notContactedCount = 0;
    let upcomingFollowUps = 0;
    let overdueFollowUps = 0;

    const now = new Date();

    leads.forEach((lead) => {
      // Status counts
      if (lead.status) {
        statusCounts[lead.status as keyof typeof statusCounts]++;
      }

      // Qualification counts - default to 'cold' if not set
      const qual = lead.qualification_level || 'cold';
      if (qual === 'hot' || qual === 'warm' || qual === 'cold') {
        qualCounts[qual]++;
      }

      // Contacted counts
      const leadActivities = activities.filter(a => a.lead_id === lead.id);
      const hasContact = leadActivities.some(a => 
        a.activity_type === "call" || a.activity_type === "email"
      );
      if (hasContact) contactedCount++;
      else notContactedCount++;

      // Follow-up counts
      const upcomingActivities = leadActivities.filter(a => 
        a.follow_up_date && !a.follow_up_completed
      );
      upcomingActivities.forEach(a => {
        const followUpDate = new Date(a.follow_up_date);
        if (followUpDate < now) {
          overdueFollowUps++;
        } else {
          upcomingFollowUps++;
        }
      });
    });

    return {
      total: leads.length,
      statusCounts,
      qualCounts,
      contactedCount,
      notContactedCount,
      upcomingFollowUps,
      overdueFollowUps,
    };
  }, [leads, activities]);

  const toggle = (id: string) => {
    setSelectedLeads((prev) => {
      const n = new Set(prev);
      if (n.has(id)) n.delete(id);
      else n.add(id);
      return Array.from(n);
    });
  };

  const enrichSelected = async () => {
    const ids = selectedLeads;
    if (ids.length === 0) return;

    console.log(`[LEADS PAGE] Starting bulk enrichment for ${ids.length} leads:`, ids);
    setEnriching(true);
    try {
      const result = await Api.enrichLeads(ids);
      console.log(`[LEADS PAGE] ✅ Bulk enrichment completed:`, result);
      alert(`Enrichment requested for ${ids.length} lead(s).`);
      await load();
    } catch (e: any) {
      console.error(`[LEADS PAGE] ❌ Bulk enrichment failed:`, e);
      alert(e.message);
    } finally {
      setEnriching(false);
    }
  };

  const enrichLead = async (leadId: string) => {
    setEnrichingSingle(leadId);
    try {
      await Api.enrichLead(leadId);
      alert("Enrichment complete! Lead data has been updated.");
      await load();
    } catch (e: any) {
      alert(`Enrichment failed: ${e.message}`);
    } finally {
      setEnrichingSingle(null);
    }
  };

  const deleteLead = async (leadId: string, leadName: string) => {
    if (!confirm(`Delete lead "${leadName}"?`)) return;
    
    try {
      await Api.deleteLead(leadId);
      await load();
    } catch (e: any) {
      alert(`Error deleting lead: ${e.message}`);
    }
  };

  const deleteSelected = async () => {
    const ids = selectedLeads;
    if (ids.length === 0) return;
    
    if (!confirm(`Delete ${ids.length} selected lead(s)?`)) return;
    
    try {
      await Api.bulkDeleteLeads(ids);
      await load();
    } catch (e: any) {
      alert(`Error deleting leads: ${e.message}`);
    }
  };

  const handleSelectAll = () => {
    if (selectedLeads.length === sorted.length) {
      setSelectedLeads([]);
    } else {
      setSelectedLeads(sorted.map(l => l.id));
    }
  };

  // Pagination calculations
  const totalItems = sorted.length;
  const totalPages = Math.ceil(totalItems / pageSize);
  const startIndex = (currentPage - 1) * pageSize;
  const endIndex = startIndex + pageSize;
  const paginatedLeads = sorted.slice(startIndex, endIndex);

  const goToPage = (page: number) => {
    setCurrentPage(Math.max(1, Math.min(page, totalPages)));
  };

  // Helper component for sortable table headers
  const SortableHeader = ({ field, label }: { field: SortField; label: string }) => (
    <button 
      onClick={() => handleSort(field)} 
      className="flex items-center gap-1.5 text-xs font-semibold text-gray-500 uppercase tracking-wider hover:text-gray-700 transition-colors text-left group"
    >
      {label}
      {sortField === field ? (
        sortDirection === "asc" ? <ArrowUp className="w-3 h-3" /> : <ArrowDown className="w-3 h-3" />
      ) : (
        <ArrowUpDown className="w-3 h-3 opacity-0 group-hover:opacity-50" />
      )}
    </button>
  );

  return (
    <AppShell
      title="Leads"
      active="leads"
      onNav={(k) => {
        if (k === "campaigns") onGoCampaigns();
        else onNav(k);
      }}
    >
      <div className="space-y-6">
        {/* Header Section */}
        <div className="space-y-4">
          {/* Tabs */}
          <div className="flex items-center gap-2 p-1 bg-gray-100 rounded-lg w-full sm:w-auto">
            <button
              onClick={() => setTab("discovered")}
              className={`
                flex-1 sm:flex-initial flex items-center justify-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all duration-150
                ${tab === "discovered"
                  ? "bg-white text-gray-900 shadow-sm"
                  : "text-gray-600 hover:text-gray-900"
                }
              `}
            >
              <Users className="w-4 h-4" />
              <span className="hidden sm:inline">Discovered</span>
              <span className="sm:hidden">Disc.</span>
              {tab === "discovered" && (
                <span className="ml-1 px-1.5 py-0.5 rounded text-xs bg-gray-100 text-gray-600">
                  {sorted.length}
                </span>
              )}
            </button>
            <button
              onClick={() => setTab("enriched")}
              className={`
                flex-1 sm:flex-initial flex items-center justify-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all duration-150
                ${tab === "enriched"
                  ? "bg-white text-gray-900 shadow-sm"
                  : "text-gray-600 hover:text-gray-900"
                }
              `}
            >
              <Sparkles className="w-4 h-4" />
              Enriched
              {tab === "enriched" && (
                <span className="ml-1 px-1.5 py-0.5 rounded text-xs bg-gray-100 text-gray-600">
                  {sorted.length}
                </span>
              )}
            </button>
          </div>

          {/* Search & Actions */}
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <input
                value={q}
                onChange={(e) => setQ(e.target.value)}
                placeholder="Search name, company, title, email..."
                className="w-full pl-10 pr-4 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-[#E64B8B]/20 focus:border-[#E64B8B] transition-all"
              />
            </div>

            <div className="flex items-center gap-2">
              {tab === "discovered" && (
                <button
                  onClick={enrichSelected}
                  disabled={enriching || selectedLeads.length === 0}
                  className={`
                    flex-1 sm:flex-initial flex items-center justify-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all border whitespace-nowrap
                    ${enriching || selectedLeads.length === 0
                      ? "bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed"
                      : "bg-white text-[#E64B8B] border-[#E64B8B] hover:bg-[#E64B8B] hover:text-white active:scale-95"
                    }
                  `}
                >
                  <Zap className="w-4 h-4" />
                  {enriching ? "Processing..." : `Enrich (${selectedLeads.length})`}
                </button>
              )}
              
              {selectedLeads.length > 0 && (
                <button
                  onClick={deleteSelected}
                  className="flex-1 sm:flex-initial flex items-center justify-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-gray-600 bg-white border border-gray-200 hover:border-red-300 hover:text-red-600 hover:bg-red-50 transition-all whitespace-nowrap active:scale-95"
                >
                  <Trash2 className="w-4 h-4" />
                  <span>Delete ({selectedLeads.length})</span>
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Info Banner */}
        <div className="bg-blue-50 border border-blue-100 rounded-lg p-3">
          <p className="text-sm text-blue-900">
            <strong>💡 Discovery-First:</strong> Review discovered leads first. Only enrich the prospects worth spending credits on.
          </p>
        </div>

        {/* Filter Blocks - Only show for enriched tab */}
        {tab === "enriched" && (
          <div className="space-y-4">
            {/* Clear Filters Button */}
            {hasActiveFilters && (
              <div className="flex items-center justify-between bg-[#E64B8B]/5 border border-[#E64B8B]/20 rounded-lg px-4 py-2">
                <div className="flex items-center gap-2 text-sm text-[#E64B8B]">
                  <Filter className="w-4 h-4" />
                  <span className="font-medium">Active filters applied</span>
                </div>
                <button
                  onClick={clearAllFilters}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-[#E64B8B] hover:bg-[#E64B8B] hover:text-white border border-[#E64B8B] rounded-lg transition-all"
                >
                  <X className="w-3 h-3" />
                  Clear All
                </button>
              </div>
            )}

            {/* Statistics Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              {/* Total Leads */}
              <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm hover:shadow-md transition-all">
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Total Leads</p>
                    <p className="text-3xl font-bold text-gray-900">{stats.total}</p>
                  </div>
                  <div className="p-2.5 bg-gray-100 rounded-lg">
                    <Users className="w-5 h-5 text-gray-600" />
                  </div>
                </div>
              </div>

              {/* Contacted Status */}
              <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Contact Status</p>
                  </div>
                  <div className="p-2.5 bg-green-100 rounded-lg">
                    <CheckCircle className="w-5 h-5 text-green-600" />
                  </div>
                </div>
                <div className="space-y-2">
                  <button
                    onClick={() => setContactedFilter(contactedFilter === true ? null : true)}
                    className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm font-medium transition-all border ${
                      contactedFilter === true
                        ? "bg-green-50 text-green-700 border-green-300 shadow-sm"
                        : "bg-gray-50 text-gray-700 border-gray-200 hover:border-gray-300"
                    }`}
                  >
                    <span>Contacted</span>
                    <span className="text-xs font-bold">{stats.contactedCount}</span>
                  </button>
                  <button
                    onClick={() => setContactedFilter(contactedFilter === false ? null : false)}
                    className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm font-medium transition-all border ${
                      contactedFilter === false
                        ? "bg-orange-50 text-orange-700 border-orange-300 shadow-sm"
                        : "bg-gray-50 text-gray-700 border-gray-200 hover:border-gray-300"
                    }`}
                  >
                    <span>Not Contacted</span>
                    <span className="text-xs font-bold">{stats.notContactedCount}</span>
                  </button>
                </div>
              </div>

              {/* Follow-ups */}
              <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Follow-ups</p>
                  </div>
                  <div className="p-2.5 bg-blue-100 rounded-lg">
                    <Calendar className="w-5 h-5 text-blue-600" />
                  </div>
                </div>
                <div className="space-y-2">
                  <button
                    onClick={() => setFollowUpFilter(followUpFilter === "upcoming" ? null : "upcoming")}
                    className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm font-medium transition-all border ${
                      followUpFilter === "upcoming"
                        ? "bg-blue-50 text-blue-700 border-blue-300 shadow-sm"
                        : "bg-gray-50 text-gray-700 border-gray-200 hover:border-gray-300"
                    }`}
                  >
                    <span className="flex items-center gap-1.5">
                      <Clock className="w-3.5 h-3.5" />
                      Upcoming
                    </span>
                    <span className="text-xs font-bold">{stats.upcomingFollowUps}</span>
                  </button>
                  <button
                    onClick={() => setFollowUpFilter(followUpFilter === "overdue" ? null : "overdue")}
                    className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm font-medium transition-all border ${
                      followUpFilter === "overdue"
                        ? "bg-red-50 text-red-700 border-red-300 shadow-sm"
                        : "bg-gray-50 text-gray-700 border-gray-200 hover:border-gray-300"
                    }`}
                  >
                    <span className="flex items-center gap-1.5">
                      <AlertCircle className="w-3.5 h-3.5" />
                      Overdue
                    </span>
                    <span className="text-xs font-bold">{stats.overdueFollowUps}</span>
                  </button>
                </div>
              </div>

              {/* Qualification Levels */}
              <div className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">Qualification</p>
                  </div>
                  <div className="p-2.5 bg-[#E64B8B]/10 rounded-lg">
                    <TrendingUp className="w-5 h-5 text-[#E64B8B]" />
                  </div>
                </div>
                <div className="space-y-2">
                  <button
                    onClick={() => setQualificationFilter(qualificationFilter === "hot" ? null : "hot")}
                    className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm font-medium transition-all border ${
                      qualificationFilter === "hot"
                        ? "bg-red-50 text-red-700 border-red-300 shadow-sm"
                        : "bg-gray-50 text-gray-700 border-gray-200 hover:border-gray-300"
                    }`}
                  >
                    <span>🔴 Hot</span>
                    <span className="text-xs font-bold">{stats.qualCounts.hot}</span>
                  </button>
                  <button
                    onClick={() => setQualificationFilter(qualificationFilter === "warm" ? null : "warm")}
                    className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm font-medium transition-all border ${
                      qualificationFilter === "warm"
                        ? "bg-orange-50 text-orange-700 border-orange-300 shadow-sm"
                        : "bg-gray-50 text-gray-700 border-gray-200 hover:border-gray-300"
                    }`}
                  >
                    <span>🟡 Warm</span>
                    <span className="text-xs font-bold">{stats.qualCounts.warm}</span>
                  </button>
                  <button
                    onClick={() => setQualificationFilter(qualificationFilter === "cold" ? null : "cold")}
                    className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-sm font-medium transition-all border ${
                      qualificationFilter === "cold"
                        ? "bg-blue-50 text-blue-700 border-blue-300 shadow-sm"
                        : "bg-gray-50 text-gray-700 border-gray-200 hover:border-gray-300"
                    }`}
                  >
                    <span>🔵 Cold</span>
                    <span className="text-xs font-bold">{stats.qualCounts.cold}</span>
                  </button>
                </div>
              </div>
            </div>

            {/* Pipeline Status Filters */}
            <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
              <h3 className="text-sm font-semibold text-gray-700 uppercase tracking-wide mb-4 flex items-center gap-2">
                <Building2 className="w-4 h-4" />
                Pipeline Status
              </h3>
              <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
                <button
                  onClick={() => setStatusFilter(statusFilter === "new" ? null : "new")}
                  className={`flex flex-col items-center justify-center px-4 py-3 rounded-lg text-sm font-medium transition-all border ${
                    statusFilter === "new"
                      ? "bg-gray-100 text-gray-800 border-gray-400 shadow-md scale-105"
                      : "bg-gray-50 text-gray-700 border-gray-200 hover:border-gray-300 hover:shadow-sm"
                  }`}
                >
                  <span className="text-lg font-bold">{stats.statusCounts.new}</span>
                  <span className="text-xs mt-1">New</span>
                </button>
                <button
                  onClick={() => setStatusFilter(statusFilter === "contacted" ? null : "contacted")}
                  className={`flex flex-col items-center justify-center px-4 py-3 rounded-lg text-sm font-medium transition-all border ${
                    statusFilter === "contacted"
                      ? "bg-blue-100 text-blue-800 border-blue-400 shadow-md scale-105"
                      : "bg-blue-50 text-blue-700 border-blue-200 hover:border-blue-300 hover:shadow-sm"
                  }`}
                >
                  <span className="text-lg font-bold">{stats.statusCounts.contacted}</span>
                  <span className="text-xs mt-1">Contacted</span>
                </button>
                <button
                  onClick={() => setStatusFilter(statusFilter === "qualified" ? null : "qualified")}
                  className={`flex flex-col items-center justify-center px-4 py-3 rounded-lg text-sm font-medium transition-all border ${
                    statusFilter === "qualified"
                      ? "bg-green-100 text-green-800 border-green-400 shadow-md scale-105"
                      : "bg-green-50 text-green-700 border-green-200 hover:border-green-300 hover:shadow-sm"
                  }`}
                >
                  <span className="text-lg font-bold">{stats.statusCounts.qualified}</span>
                  <span className="text-xs mt-1">Qualified</span>
                </button>
                <button
                  onClick={() => setStatusFilter(statusFilter === "proposal" ? null : "proposal")}
                  className={`flex flex-col items-center justify-center px-4 py-3 rounded-lg text-sm font-medium transition-all border ${
                    statusFilter === "proposal"
                      ? "bg-purple-100 text-purple-800 border-purple-400 shadow-md scale-105"
                      : "bg-purple-50 text-purple-700 border-purple-200 hover:border-purple-300 hover:shadow-sm"
                  }`}
                >
                  <span className="text-lg font-bold">{stats.statusCounts.proposal}</span>
                  <span className="text-xs mt-1">Proposal</span>
                </button>
                <button
                  onClick={() => setStatusFilter(statusFilter === "won" ? null : "won")}
                  className={`flex flex-col items-center justify-center px-4 py-3 rounded-lg text-sm font-medium transition-all border ${
                    statusFilter === "won"
                      ? "bg-emerald-100 text-emerald-800 border-emerald-400 shadow-md scale-105"
                      : "bg-emerald-50 text-emerald-700 border-emerald-200 hover:border-emerald-300 hover:shadow-sm"
                  }`}
                >
                  <span className="text-lg font-bold">{stats.statusCounts.won}</span>
                  <span className="text-xs mt-1">Won</span>
                </button>
                <button
                  onClick={() => setStatusFilter(statusFilter === "lost" ? null : "lost")}
                  className={`flex flex-col items-center justify-center px-4 py-3 rounded-lg text-sm font-medium transition-all border ${
                    statusFilter === "lost"
                      ? "bg-red-100 text-red-800 border-red-400 shadow-md scale-105"
                      : "bg-red-50 text-red-700 border-red-200 hover:border-red-300 hover:shadow-sm"
                  }`}
                >
                  <span className="text-lg font-bold">{stats.statusCounts.lost}</span>
                  <span className="text-xs mt-1">Lost</span>
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Table */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
          {/* Error Message */}
          {error && (
            <div className="px-6 py-8 bg-yellow-50 border-b border-yellow-200">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 rounded-full bg-yellow-100 flex items-center justify-center flex-shrink-0">
                  <span className="text-2xl">⚠️</span>
                </div>
                <div className="flex-1">
                  <h3 className="font-bold text-yellow-900 mb-2">Backend Not Deployed</h3>
                  <p className="text-sm text-yellow-800 mb-3">{error}</p>
                  <div className="bg-white rounded-lg p-4 border border-yellow-200">
                    <p className="text-xs text-gray-700 font-semibold mb-2">📋 To deploy the Supabase Edge Function:</p>
                    <ol className="text-xs text-gray-600 space-y-1 list-decimal list-inside">
                      <li>Open your <strong>Supabase Dashboard</strong></li>
                      <li>Go to <strong>Edge Functions</strong> in the sidebar</li>
                      <li>Deploy the <code className="bg-gray-100 px-1 rounded">make-server-2f1627d1</code> function</li>
                      <li>Refresh this page</li>
                    </ol>
                    <p className="text-xs text-gray-500 mt-3">
                      Alternatively, use the Supabase CLI: <code className="bg-gray-100 px-2 py-1 rounded text-[10px]">supabase functions deploy make-server-2f1627d1</code>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          {/* Table Header - Different for each tab - Hidden on mobile */}
          {tab === "enriched" ? (
            <div className="hidden lg:grid grid-cols-[40px_1.4fr_1.4fr_1fr_1.2fr_1fr_1fr_1fr_100px] gap-4 px-6 py-4 bg-gray-50 border-b border-gray-200">
              <div className="flex items-center">
                <input 
                  type="checkbox" 
                  checked={sorted.length > 0 && selectedLeads.length === sorted.length}
                  onChange={handleSelectAll}
                  className="w-4 h-4 rounded border-gray-300 text-[#E64B8B] focus:ring-[#E64B8B]/20 cursor-pointer"
                  title="Select all"
                />
              </div>
              <SortableHeader field="name" label="Person" />
              <SortableHeader field="company" label="Company" />
              <SortableHeader field="status" label="Status" />
              <SortableHeader field="qualification" label="Qualification" />
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Contacted</div>
              <SortableHeader field="followUp" label="Follow-up" />
              <SortableHeader field="added" label="Added" />
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Actions</div>
            </div>
          ) : (
            <div className="hidden lg:grid grid-cols-[40px_1.2fr_1.4fr_1fr_0.7fr_1fr_1fr_1fr_100px] gap-4 px-6 py-4 bg-gray-50 border-b border-gray-200">
              <div className="flex items-center">
                <input 
                  type="checkbox" 
                  checked={sorted.length > 0 && selectedLeads.length === sorted.length}
                  onChange={handleSelectAll}
                  className="w-4 h-4 rounded border-gray-300 text-[#E64B8B] focus:ring-[#E64B8B]/20 cursor-pointer"
                  title="Select all"
                />
              </div>
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Person</div>
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Company</div>
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Title</div>
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Apollo ID</div>
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Email</div>
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Phone</div>
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Added (CST)</div>
              <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Actions</div>
            </div>
          )}

          {/* Table Body */}
          <div className="divide-y divide-gray-100">
            {loading ? (
              <div className="px-6 py-12 text-center">
                <div className="inline-flex items-center gap-3 text-gray-500">
                  <div className="w-5 h-5 border-2 border-gray-300 border-t-[#E64B8B] rounded-full animate-spin"></div>
                  Loading leads...
                </div>
              </div>
            ) : paginatedLeads.length === 0 ? (
              <div className="px-6 py-12 text-center">
                <Users className="w-12 h-12 text-gray-300 mx-auto mb-3" />
                <p className="text-gray-500 font-medium">No leads found</p>
                <p className="text-sm text-gray-400 mt-1">Try adjusting your search or import new leads</p>
              </div>
            ) : tab === "enriched" ? (
              // Enriched Tab Row Layout
              paginatedLeads.map((l) => {
                const id = l.id;
                const name = `${l.first_name ?? ""} ${l.last_name ?? ""}`.trim() || "—";
                const company = l.company_name ?? "—";
                const title = l.title ?? "—";

                // Status & Qualification
                const statusConfig = {
                  new: { label: "New", color: "bg-gray-100 text-gray-700" },
                  contacted: { label: "Contacted", color: "bg-blue-100 text-blue-700" },
                  qualified: { label: "Qualified", color: "bg-green-100 text-green-700" },
                  proposal: { label: "Proposal", color: "bg-purple-100 text-purple-700" },
                  won: { label: "Won", color: "bg-emerald-100 text-emerald-700" },
                  lost: { label: "Lost", color: "bg-red-100 text-red-700" },
                };
                const qualConfig = {
                  cold: { icon: "🔵", label: "Cold", color: "bg-blue-100 text-blue-700" },
                  warm: { icon: "🟡", label: "Warm", color: "bg-orange-100 text-orange-700" },
                  hot: { icon: "🔴", label: "Hot", color: "bg-red-100 text-red-700" },
                };
                const validStatuses = Object.keys(statusConfig) as Array<keyof typeof statusConfig>;
                const validQuals = Object.keys(qualConfig) as Array<keyof typeof qualConfig>;
                const currentStatus = validStatuses.includes(l.status as any) ? (l.status as keyof typeof statusConfig) : "new";
                const currentQual = validQuals.includes(l.qualification_level as any) ? (l.qualification_level as keyof typeof qualConfig) : "cold";

                // Activity data
                const leadActivities = activities.filter(a => a.lead_id === id);
                const hasContact = leadActivities.some(a => a.activity_type === "call" || a.activity_type === "email");
                const upcomingFollowUps = leadActivities.filter(a => a.follow_up_date && !a.follow_up_completed);
                const nextFollowUp = upcomingFollowUps.length > 0
                  ? upcomingFollowUps.reduce((earliest, current) => {
                      const currentDate = new Date(current.follow_up_date);
                      const earliestDate = new Date(earliest.follow_up_date);
                      return currentDate < earliestDate ? current : earliest;
                    })
                  : null;
                const followUpDate = nextFollowUp ? new Date(nextFollowUp.follow_up_date) : null;
                const isOverdue = followUpDate && followUpDate < new Date();

                return (
                  <div key={id}>
                    {/* Desktop Table Row */}
                    <div className="hidden lg:grid grid-cols-[40px_1.4fr_1.4fr_1fr_1.2fr_1fr_1fr_1fr_100px] gap-4 px-6 py-4 hover:bg-gray-50 transition-colors">
                      <div className="flex items-center">
                        <input 
                          type="checkbox" 
                          checked={selectedLeads.includes(id)} 
                          onChange={() => toggle(id)}
                          className="w-4 h-4 rounded border-gray-300 text-[#E64B8B] focus:ring-[#E64B8B]/20 cursor-pointer"
                        />
                      </div>
                      <div>
                        <div className="font-semibold text-gray-900">{name}</div>
                        <div className="text-xs text-gray-500 mt-0.5">{title}</div>
                      </div>
                      <div>
                        <div className="font-medium text-gray-900">{company}</div>
                        {l.company_domain && (
                          <div className="text-xs text-gray-500 mt-0.5">{l.company_domain}</div>
                        )}
                      </div>
                      <div className="flex items-center">
                        <span className={`px-2.5 py-1 rounded-md text-xs font-medium ${statusConfig[currentStatus].color}`}>
                          {statusConfig[currentStatus].label}
                        </span>
                      </div>
                      <div className="flex items-center">
                        <span className={`px-2.5 py-1 rounded-md text-xs font-medium ${qualConfig[currentQual].color}`}>
                          {qualConfig[currentQual].icon} {qualConfig[currentQual].label}
                        </span>
                      </div>
                      <div className="flex items-center">
                        {hasContact ? (
                          <span className="flex items-center gap-1 px-2.5 py-1 rounded-md text-xs font-medium bg-green-100 text-green-700">
                            <CheckCircle className="w-3 h-3" />
                            Yes
                          </span>
                        ) : (
                          <span className="flex items-center gap-1 px-2.5 py-1 rounded-md text-xs font-medium bg-gray-100 text-gray-600">
                            <X className="w-3 h-3" />
                            No
                          </span>
                        )}
                      </div>
                      <div className="flex items-center">
                        {nextFollowUp ? (
                          <div className="flex items-start gap-1.5">
                            {isOverdue ? (
                              <AlertCircle className="w-3.5 h-3.5 text-red-600 mt-0.5 flex-shrink-0" />
                            ) : (
                              <Clock className="w-3.5 h-3.5 text-blue-600 mt-0.5 flex-shrink-0" />
                            )}
                            <div>
                              <div className={`text-xs font-medium ${isOverdue ? "text-red-700" : "text-blue-700"}`}>
                                {formatShortDate(nextFollowUp.follow_up_date)}
                              </div>
                              {nextFollowUp.follow_up_action && (
                                <div className="text-[10px] text-gray-500 mt-0.5">{nextFollowUp.follow_up_action}</div>
                              )}
                            </div>
                          </div>
                        ) : (
                          <span className="text-xs text-gray-400">—</span>
                        )}
                      </div>
                      <div className="flex items-center text-xs text-gray-500">{formatShortDate(l.created_at)}</div>
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => onNav("lead-detail", { leadId: id, fromTab: tab })}
                          className="p-2 rounded-lg text-gray-600 hover:bg-gray-100 hover:text-[#E64B8B] transition-all"
                          title="View details"
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => deleteLead(id, name)}
                          className="p-2 rounded-lg text-red-600 hover:bg-red-50 transition-all"
                          title="Delete"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    {/* Mobile Card */}
                    <div className="lg:hidden p-4 border-b border-gray-100 hover:bg-gray-50 transition-colors">
                      <div className="flex items-start gap-3">
                        <input 
                          type="checkbox" 
                          checked={selectedLeads.includes(id)} 
                          onChange={() => toggle(id)}
                          className="w-5 h-5 mt-1 rounded border-gray-300 text-[#E64B8B] focus:ring-[#E64B8B]/20 cursor-pointer"
                        />
                        <div className="flex-1 min-w-0">
                          {/* Name & Company */}
                          <div className="mb-3">
                            <h3 className="font-semibold text-gray-900 text-base">{name}</h3>
                            <p className="text-sm text-gray-600 mt-0.5">{title}</p>
                            <div className="flex items-center gap-1.5 mt-1">
                              <Building2 className="w-3.5 h-3.5 text-gray-400" />
                              <p className="text-sm font-medium text-gray-700">{company}</p>
                            </div>
                          </div>

                          {/* Status & Qualification */}
                          <div className="flex items-center gap-2 mb-3">
                            <span className={`px-2.5 py-1 rounded-md text-xs font-medium ${statusConfig[currentStatus].color}`}>
                              {statusConfig[currentStatus].label}
                            </span>
                            <span className={`px-2.5 py-1 rounded-md text-xs font-medium ${qualConfig[currentQual].color}`}>
                              {qualConfig[currentQual].icon} {qualConfig[currentQual].label}
                            </span>
                          </div>

                          {/* Contact & Follow-up */}
                          <div className="grid grid-cols-2 gap-3 mb-3 text-sm">
                            <div>
                              <p className="text-xs text-gray-500 mb-1">Contacted</p>
                              {hasContact ? (
                                <span className="inline-flex items-center gap-1 text-green-700 font-medium">
                                  <CheckCircle className="w-3.5 h-3.5" />
                                  Yes
                                </span>
                              ) : (
                                <span className="inline-flex items-center gap-1 text-gray-600">
                                  <X className="w-3.5 h-3.5" />
                                  No
                                </span>
                              )}
                            </div>
                            <div>
                              <p className="text-xs text-gray-500 mb-1">Follow-up</p>
                              {nextFollowUp ? (
                                <span className={`inline-flex items-center gap-1 font-medium ${isOverdue ? "text-red-700" : "text-blue-700"}`}>
                                  {isOverdue ? <AlertCircle className="w-3.5 h-3.5" /> : <Clock className="w-3.5 h-3.5" />}
                                  {formatShortDate(nextFollowUp.follow_up_date)}
                                </span>
                              ) : (
                                <span className="text-gray-400">—</span>
                              )}
                            </div>
                          </div>

                          {/* Actions */}
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => onNav("lead-detail", { leadId: id, fromTab: tab })}
                              className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium text-white bg-[#E64B8B] hover:bg-[#d43d7a] transition-all"
                            >
                              <Eye className="w-4 h-4" />
                              View Details
                            </button>
                            <button
                              onClick={() => deleteLead(id, name)}
                              className="p-2.5 rounded-lg text-red-600 bg-red-50 hover:bg-red-100 transition-all"
                              title="Delete"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })
            ) : (
              // Discovered Tab Row Layout
              paginatedLeads.map((l) => {
                const id = l.id;
                const name = `${l.first_name ?? ""} ${l.last_name ?? ""}`.trim() || "—";
                const company = l.company_name ?? "—";
                const title = l.title ?? "—";
                const email = l.email || l.enrichment?.email || "—";
                const phone = l.phone || l.enrichment?.phone || "—";
                const addedDate = formatDateCST(l.created_at);
                const hasApolloId = !!l.apollo_id;

                return (
                  <div key={id}>
                    {/* Desktop Table Row */}
                    <div className="hidden lg:grid grid-cols-[40px_1.2fr_1.4fr_1fr_0.7fr_1fr_1fr_1fr_100px] gap-4 px-6 py-4 hover:bg-gray-50 transition-colors">
                      <div className="flex items-center">
                        <input 
                          type="checkbox" 
                          checked={selectedLeads.includes(id)} 
                          onChange={() => toggle(id)}
                          className="w-4 h-4 rounded border-gray-300 text-[#E64B8B] focus:ring-[#E64B8B]/20 cursor-pointer"
                        />
                      </div>
                      <div>
                        <div className="font-semibold text-gray-900">{name}</div>
                        <div className="flex items-center gap-2 mt-1">
                          {l.city && (
                            <span className="text-xs text-gray-500 flex items-center gap-1">
                              <MapPin className="w-3 h-3" />
                              {l.city}{l.state ? `, ${l.state}` : ""}
                            </span>
                          )}
                          {hasApolloId && (
                            <span className="text-[10px] font-bold text-white bg-gradient-to-r from-[#E64B8B] to-[#d43d7a] px-2 py-0.5 rounded-full">
                              APOLLO
                            </span>
                          )}
                        </div>
                      </div>
                      <div>
                        <div className="font-semibold text-gray-900">{company}</div>
                        {l.company_domain && (
                          <div className="text-xs text-gray-500 mt-1">{l.company_domain}</div>
                        )}
                      </div>
                      <div className="text-sm text-gray-700">{title}</div>
                      <div className="text-xs text-gray-500 font-mono truncate" title={l.apollo_id || ''}>
                        {l.apollo_id ? `${l.apollo_id.substring(0, 8)}...` : "—"}
                      </div>
                      <div className="text-sm text-gray-700 truncate" title={email}>{email}</div>
                      <div className="text-sm text-gray-700">{phone}</div>
                      <div className="text-xs text-gray-500">{addedDate}</div>
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => onNav("lead-detail", { leadId: id, fromTab: tab })}
                          className="p-2 rounded-lg text-gray-600 hover:bg-gray-100 hover:text-[#E64B8B] transition-all"
                          title="View details"
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                        {l.enrichment_status !== "complete" && hasApolloId && (
                          <button
                            onClick={() => enrichLead(id)}
                            disabled={enrichingSingle === id}
                            className="p-2 rounded-lg text-[#E64B8B] hover:bg-pink-50 transition-all disabled:opacity-50"
                            title="Enrich lead"
                          >
                            <Sparkles className="w-4 h-4" />
                          </button>
                        )}
                        <button
                          onClick={() => deleteLead(id, name)}
                          className="p-2 rounded-lg text-red-600 hover:bg-red-50 transition-all"
                          title="Delete"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    {/* Mobile Card */}
                    <div className="lg:hidden p-4 border-b border-gray-100 hover:bg-gray-50 transition-colors">
                      <div className="flex items-start gap-3">
                        <input 
                          type="checkbox" 
                          checked={selectedLeads.includes(id)} 
                          onChange={() => toggle(id)}
                          className="w-5 h-5 mt-1 rounded border-gray-300 text-[#E64B8B] focus:ring-[#E64B8B]/20 cursor-pointer"
                        />
                        <div className="flex-1 min-w-0">
                          {/* Name & Company */}
                          <div className="mb-3">
                            <h3 className="font-semibold text-gray-900 text-base">{name}</h3>
                            <p className="text-sm text-gray-600 mt-0.5">{title}</p>
                            <div className="flex items-center gap-1.5 mt-1">
                              <Building2 className="w-3.5 h-3.5 text-gray-400" />
                              <p className="text-sm font-medium text-gray-700">{company}</p>
                            </div>
                            {l.city && (
                              <div className="flex items-center gap-1 mt-1">
                                <MapPin className="w-3 h-3 text-gray-400" />
                                <span className="text-xs text-gray-500">
                                  {l.city}{l.state ? `, ${l.state}` : ""}
                                </span>
                              </div>
                            )}
                            {hasApolloId && (
                              <span className="inline-block mt-2 text-[10px] font-bold text-white bg-gradient-to-r from-[#E64B8B] to-[#d43d7a] px-2 py-0.5 rounded-full">
                                APOLLO
                              </span>
                            )}
                          </div>

                          {/* Contact Info */}
                          <div className="mb-3 space-y-1.5 text-sm">
                            {email !== "—" && (
                              <div className="flex items-center gap-2">
                                <Mail className="w-3.5 h-3.5 text-gray-400" />
                                <span className="text-gray-700 truncate">{email}</span>
                              </div>
                            )}
                            {phone !== "—" && (
                              <div className="flex items-center gap-2">
                                <Phone className="w-3.5 h-3.5 text-gray-400" />
                                <span className="text-gray-700">{phone}</span>
                              </div>
                            )}
                          </div>

                          {/* Actions */}
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => onNav("lead-detail", { leadId: id, fromTab: tab })}
                              className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium text-white bg-[#E64B8B] hover:bg-[#d43d7a] transition-all"
                            >
                              <Eye className="w-4 h-4" />
                              View Details
                            </button>
                            {l.enrichment_status !== "complete" && hasApolloId && (
                              <button
                                onClick={() => enrichLead(id)}
                                disabled={enrichingSingle === id}
                                className="p-2.5 rounded-lg text-[#E64B8B] bg-pink-50 hover:bg-pink-100 transition-all disabled:opacity-50"
                                title="Enrich lead"
                              >
                                <Sparkles className="w-4 h-4" />
                              </button>
                            )}
                            <button
                              onClick={() => deleteLead(id, name)}
                              className="p-2.5 rounded-lg text-red-600 bg-red-50 hover:bg-red-100 transition-all"
                              title="Delete"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })
            )}
          </div>

          {/* Pagination Controls */}
          {totalItems > 0 && (
            <div className="flex flex-col sm:flex-row items-center justify-between gap-4 px-4 sm:px-6 py-4 border-t border-gray-200 bg-gray-50">
              {/* Left: Pagination info */}
              <div className="flex flex-col sm:flex-row items-center gap-3 sm:gap-4 w-full sm:w-auto">
                <div className="text-sm text-gray-600 text-center sm:text-left">
                  Showing <span className="font-semibold text-gray-900">{startIndex + 1}</span> to{" "}
                  <span className="font-semibold text-gray-900">{Math.min(endIndex, totalItems)}</span> of{" "}
                  <span className="font-semibold text-gray-900">{totalItems}</span> leads
                </div>
                <div className="flex items-center gap-2">
                  <label htmlFor="page-size" className="text-sm text-gray-600">
                    Show:
                  </label>
                  <select
                    id="page-size"
                    value={pageSize}
                    onChange={(e) => {
                      setPageSize(Number(e.target.value));
                      setCurrentPage(1);
                    }}
                    className="px-3 py-1.5 text-sm border border-gray-200 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-[#E64B8B]/20 focus:border-[#E64B8B] cursor-pointer"
                  >
                    <option value={20}>20</option>
                    <option value={25}>25</option>
                    <option value={50}>50</option>
                    <option value={75}>75</option>
                    <option value={100}>100</option>
                  </select>
                </div>
              </div>

              {/* Right: Page navigation */}
              {totalPages > 1 && (
                <div className="flex items-center gap-2 w-full sm:w-auto justify-center">
                  <button
                    onClick={() => goToPage(currentPage - 1)}
                    disabled={currentPage === 1}
                    className={`flex items-center gap-1 px-3 py-2 rounded-lg text-sm font-medium transition-all border ${
                      currentPage === 1
                        ? "bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed"
                        : "bg-white text-[#E64B8B] border-[#E64B8B] hover:bg-[#E64B8B] hover:text-white active:scale-95"
                    }`}
                  >
                    <ChevronLeft className="w-4 h-4" />
                    <span className="hidden sm:inline">Previous</span>
                  </button>
                  <div className="text-sm text-gray-600 px-2">
                    <span className="font-semibold text-gray-900">{currentPage}</span>
                    <span className="mx-1">/</span>
                    <span className="font-semibold text-gray-900">{totalPages}</span>
                  </div>
                  <button
                    onClick={() => goToPage(currentPage + 1)}
                    disabled={currentPage === totalPages}
                    className={`flex items-center gap-1 px-3 py-2 rounded-lg text-sm font-medium transition-all border ${
                      currentPage === totalPages
                        ? "bg-gray-100 text-gray-400 border-gray-200 cursor-not-allowed"
                        : "bg-white text-[#E64B8B] border-[#E64B8B] hover:bg-[#E64B8B] hover:text-white active:scale-95"
                    }`}
                  >
                    <span className="hidden sm:inline">Next</span>
                    <ChevronRight className="w-4 h-4" />
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </AppShell>
  );
}