import { createClient } from "@supabase/supabase-js";

// Import from autogenerated info file
// @ts-ignore - This is an autogenerated file outside of src
import { projectId, publicAnonKey } from "/utils/supabase/info";

// Singleton Supabase client to avoid multiple instances
let supabaseClient: ReturnType<typeof createClient> | null = null;

export function getSupabaseClient() {
  if (!supabaseClient) {
    supabaseClient = createClient(
      `https://${projectId}.supabase.co`,
      publicAnonKey,
      {
        auth: {
          persistSession: true,
          autoRefreshToken: true,
          detectSessionInUrl: true,
          storage: window.localStorage,
        },
      }
    );
  }
  return supabaseClient;
}